name: Build Jekyll Site
on:
  push:
  schedule:
    - cron: '0 0 5 * *'

jobs:
  Build-Jekyll:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Bundler
        runs: gem install bundler
      - name: Run bundle install
        runs: bundle install
      - name: Build Jekyll site
        runs: bundle exec jekyll build
