name: CI
on:
  pull_request:

jobs:
  Build-PR:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 14]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jvm_version }}
      - uses: actions/checkout@v2
      - shell: bash 
        run: ./gradlew check
