name: Deploy Github Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: DanySK/autodelivery
      with:
        CONFIGURATION_FILE: 'autodelivery.yml'
        GITHUB_USER: DanySK
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
