name: Deploy Github Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: DanySK/autodelivery@master
      with:
        confguration_file: 'autodelivery.yml'
        user: DanySK
        token: ${{ secrets.GH_TOKEN }}
