name: Deploy Github Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@722adc6
    - name: Deploy to DanySK/Upgradle
      uses: MikeHamilton-RW/deploy-common-actions@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: "DanySK"
        REPOSITORY: "upgradle"
        DEVELOPMENT_BRANCH: "master"
        GHA_DEPLOYMENT_FOLDER: "gradle-check-central"
        COMMIT_MESSAGE: GHA CI Update ${{ github.event.head_commit.message }}
        GHA_DEPLOY_BRANCH_NAME: gh_actions_${{ github.event.head_commit.abbreviatedOid }}
