name: Delivery

on:
  push:

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - uses: DanySK/autodelivery@master
      env:
        AUTOMERGE_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      with:
        configuration_file: 'auto-delivery.yml'
        user: DanySK
        token: ${{ secrets.GH_TOKEN }}
        commit_author: Danilo Pianini
        author_email: danilo.pianini@gmail.com
