name: Deploy Github Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: DanySK/autodelivery@master
      env:
        AUTOMERGE_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      with:
        configuration_file: 'auto-delivery.yml'
        user: DanySK
        token: ${{ secrets.GH_TOKEN }}
        commit_author: Danilo Pianini
        author_email: danilo.pianini@gmail.com
